---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Django
        uses: pip install -r requirements.txt
      - name: Test
        run: python manage.py test
      - name: Lint
        run: flake8
        